### ISSUE TITLE
Only 7 seconds can be played 

### ISSUE THREAD

**Issue by marneu** [Centurix/idrivetools#2]
After running the bmxunpack part for a new BMW model I would need the plain .wma files or alternatively files as .mp3.
Coming from a .BR5 format the conversion runs quickly but from every resulting .wma file only 7 seconds can be played. 
What am I doing wrong here?
Thanks for any help...

**Comment by Centurix** [comment]
Thank for reporting this. I've found that some iDrive systems will either convert the file extensions from WMA to BR5 or BR29 and I never really understood why it chooses one over another. The systems I've come across so far have converted to BR29 and and BR5 was suggested to me to add to the list. I suspect that the BR5 file format is encrypted past the 0x20000 byte mark, most files encrypted by iDrive only encrypt this first block.

I've created a branch in this repo to test this by extending the decryption block to the whole file. Would you be able to check to see if this addresses the issue? Sadly, I no longer have access to an iDrive system to test these things.

**Comment by Centurix** [comment]
The branch is part of this PR: https://github.com/Centurix/idrivetools/pull/3

**Comment by Centurix** [comment]
Managed to check this on a friends iDrive. It seems to have fixed the issue. Merged to the master branch. Should be OK.
